FROM jfroche/docker-plone:4.3

USER root
RUN apt-get update && apt-get install -y unzip tmux silversearcher-ag zsh exuberant-ctags parallel python-setuptools
RUN pip install watchdog pyflakes pep8 flake8 pylint zest.releaser pyroma check-manifest git+git://github.com/yejianye/watchdog-tricks.git
RUN gem install tmuxinator
RUN mkdir -p /code/.ssh
RUN echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /code/.ssh/config
RUN echo "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> /code/.ssh/config
ADD . /code/
RUN usermod -u $USERID plone
RUN chown -R plone /code
USER plone
RUN bin/buildout -N -vvv
